name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm
      - name: WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Install deps
        run: pnpm install

      - name: Cache build files
        uses: actions/cache@v2
        env:
          cache-name: cache-build-files
        with:
          path: |
            target
            dist
            dist-wasm
            svg2png_wasm_bg.wasm
          key: ${{ env.cache-name }}-${{ github.sha }}

      - name: Prebuild
        run: cargo build --target wasm32-unknown-unknown --release
      - name: Build packages
        run: pnpm make
      # fallback https://github.com/actions/cache/issues/362
      - uses: actions/upload-artifact@v2
        with:
          name: build-cache-${{ github.sha }}
          path: |
            target
            dist
            dist-wasm
            svg2png_wasm_bg.wasm

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    needs: [setup]
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [14, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install deps
        run: pnpm install

      - name: Restore build files
        uses: actions/cache@v2
        env:
          cache-name: cache-build-files
        with:
          path: |
            target
            dist
            dist-wasm
            svg2png_wasm_bg.wasm
          key: '${{ env.cache-name }}-${{ github.sha }}'
          restore-keys: |
            ${{ env.cache-name }}

      # fallback https://github.com/actions/cache/issues/362
      - uses: actions/download-artifact@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          name: build-cache-${{ github.sha }}

      - name: Test
        run: pnpm test

  other-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [setup]
    env:
      WORKING_DIR_SITE: site
      WORKING_DIR_BENCH: benchmark
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install deps
        run: pnpm install

      - name: Restore build files
        uses: actions/cache@v2
        env:
          cache-name: cache-build-files
        with:
          path: |
            target
            dist
            dist-wasm
            svg2png_wasm_bg.wasm
          key: '${{ env.cache-name }}-${{ github.sha }}'
          restore-keys: |
            ${{ env.cache-name }}

      # site checks
      - run: pnpm check
        working-directory: ${{ env.WORKING_DIR_SITE }}
      - run: pnpm build
        working-directory: ${{ env.WORKING_DIR_SITE }}
      # bench checks
      - run: pnpm check
        working-directory: ${{ env.WORKING_DIR_BENCH }}
      - run: pnpm build
        working-directory: ${{ env.WORKING_DIR_BENCH }}
